name: konzo
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - snakemake-minimal=7.32.4
  - fastqc=0.12.1
  - snakemake-wrapper-utils=0.6.2
  - multiqc=1.29
  - trimmomatic=0.39
  - kneaddata=0.12.1
  - ribodetector=0.3.1
  - bowtie2=2.5.4
  - samtools=1.22.1
  - metaphlan=4.2.4
