# imports
import os
import glob


# define base directory
BASE = "/project/blekhman/sjarif/konzo/01_MT_initialQC_HMP"
FASTQ_DIR = "/project/blekhman/shared/konzo/HMP/raw_fastq/MTX" 
# JJ already trimmed and dehosted the files (although he doesn't know the exact steps)
# I will have to add that in later to 01_MT_initialQC and 02_MT_trim_dehost
# so here I'm skipping step 01 and 02 but this code can be recycled to start from raw reads

# Create directories if they do not exist
os.makedirs(f"{BASE}/raw_reads", exist_ok=True)
os.makedirs(f"{BASE}/raw_reads/logs", exist_ok=True)
os.makedirs(f"{BASE}/raw_reads/zip", exist_ok=True)
os.makedirs(f"{BASE}/raw_reads/unzip", exist_ok=True)
os.makedirs(f"{BASE}/raw_reads/html", exist_ok=True)
os.makedirs(f"{BASE}/raw_reads/multiQC", exist_ok=True)

samples = sorted([
    os.path.basename(f).replace(".fastq.gz", "")
    for f in glob.glob(f"{FASTQ_DIR}/*.fastq.gz")
])

rule all:
    input:
        expand(BASE + "/raw_reads/zip/{sample}_fastqc.zip", sample=samples),
        BASE + "/raw_reads/multiQC/multiqc_report.html"

rule fastqc:
    input:
        f"{FASTQ_DIR}/{{sample}}.fastq.gz"
    output:
        html = BASE + "/raw_reads/html/{sample}_fastqc.html",
        zip = BASE + "/raw_reads/zip/{sample}_fastqc.zip"
    params:
        extra = "--quiet"
    log:
        BASE + "/raw_reads/logs/{sample}.log"
    threads: 1
    resources:
        mem_mb = 1024
    wrapper:
        "v5.7.0/bio/fastqc"

# Unzip each FastQC zip file (so MultiQC can read them)
rule unzip_fastqc:
    input:
        BASE + "/raw_reads/zip/{sample}_fastqc.zip"
    output:
        directory(BASE + "/raw_reads/unzip/{sample}_fastqc")
    shell:
        """
        unzip -o {input} -d {BASE}/raw_reads/unzip
        """

# Run MultiQC on all FastQC outputs
rule multiqc:
    input:
        expand(BASE + "/raw_reads/unzip/{sample}_fastqc", sample=samples)
    output:
        BASE + "/raw_reads/multiQC/multiqc_report.html"
    shell:
        """
        multiqc {BASE}/raw_reads/unzip -o {BASE}/raw_reads/multiQC
        """

