  ## IMPORTS

import glob
import re
import os

## PATHS AND VARIABLES

# project directories
project_dir="/project/blekhman/sjarif/konzo"
scratch_dir="/scratch/midway3/sjarif/konzo_scratch"
rawfile_dir = os.path.join(project_dir, "test_files")

# define sample names  
files = glob.glob(os.path.join(rawfile_dir, "*_R[12]_001.fastq.gz"))
sample_names = set(re.sub(r'_R[12]_001\.fastq\.gz$', '', os.path.basename(f)) for f in files)


## SNAKEMAKE

rule all: # End of each branch, don't necessarily need to list intermediate files
    input: # here's where you should list the FINAL files you're working toward
        expand("/scratch/midway3/sjarif/konzo_scratch/kneaddata/{sampname}_R1_001_kneaddata_trimmed_rrnadep_kneaddata_unmatched_1.fastq", sampname=sample_names),
        expand("/scratch/midway3/sjarif/konzo_scratch/kneaddata/{sampname}_R1_001_kneaddata_trimmed_rrnadep_kneaddata_unmatched_2.fastq", sampname=sample_names)

rule kneaddata_trim_rrna:
    input:
        fwd_in="/project/blekhman/sjarif/konzo/test_files/{sampname}_R1_001.fastq.gz",
        rvs_in="/project/blekhman/sjarif/konzo/test_files/{sampname}_R2_001.fastq.gz"
    output:
        # USING UNMATCHED FILES DUE TO BUG. I DON'T BELIEVE IT CHANGES ANYTHING FOR OUR PURPOSES
        # THIS IS A COMMON KNEADDATA ERROR THAT STILL HASN'T BEEN ADDRESSED IN LATEST UPDATE
        "/scratch/midway3/sjarif/konzo_scratch/kneaddata/{sampname}_R1_001_kneaddata_unmatched_1.fastq",
        "/scratch/midway3/sjarif/konzo_scratch/kneaddata/{sampname}_R1_001_kneaddata_unmatched_2.fastq"
    threads: 2
    resources:
        mem_mb=100000,
        runtime=2000
    params:
        job_name = 'kneaddata_trim_rrna'
    run:
        shell('kneaddata \
        --input1 {input.fwd_in} \
        --input2 {input.rvs_in} \
        --output /scratch/midway3/sjarif/konzo_scratch/kneaddata \
        --threads 2 \
        --sequencer-source NexteraPE \
        --run-fastqc-start \
        --run-fastqc-end \
        --trimmomatic /project/blekhman/sjarif/conda/envs/konzo_QC/share/trimmomatic-0.39-2 \
        --trimmomatic-options="LEADING:3" \
        --trimmomatic-options="TRAILING:3" \
        --trimmomatic-options="SLIDINGWINDOW:5:20" \
        --trimmomatic-options="MINLEN:50" \
        --bypass-trf \
        --reference-db /project/blekhman/sjarif/konzo/db/bact_rrna_db')
      
    
rule rename_kneaddata:
    input:
        fwd_in="/scratch/midway3/sjarif/konzo_scratch/kneaddata/{sampname}_R1_001_kneaddata_unmatched_1.fastq",
        rvs_in="/scratch/midway3/sjarif/konzo_scratch/kneaddata/{sampname}_R1_001_kneaddata_unmatched_2.fastq"
    output:
        fwd_out="/scratch/midway3/sjarif/konzo_scratch/kneaddata/{sampname}_R1_001_trimmed_rrnadep.fastq",
        rvs_out="/scratch/midway3/sjarif/konzo_scratch/kneaddata/{sampname}_R2_001_trimmed_rrnadep.fastq"
    threads: 2
    resources:
        mem_mb=8000,
        runtime=60
    params:
        job_name = 'rename_kneaddata'
    run:
        mv {input.fwd_in}{output.fwd_out}
        mv {input.rvs_in}{output.rvs_out}
        

rule kneaddata_dehost:
    input:
        fwd_in="/scratch/midway3/sjarif/konzo_scratch/kneaddata/{sampname}_R1_001_trimmed_rrnadep.fastq",
        rvs_in="/scratch/midway3/sjarif/konzo_scratch/kneaddata/{sampname}_R2_001_trimmed_rrnadep.fastq"
    output:
        # USING UNMATCHED FILES DUE TO BUG. I DON'T BELIEVE IT CHANGES ANYTHING FOR OUR PURPOSES
        # THIS IS A COMMON KNEADDATA ERROR THAT STILL HASN'T BEEN ADDRESSED IN LATEST UPDATE
        "/scratch/midway3/sjarif/konzo_scratch/kneaddata/{sampname}_R1_001_kneaddata_trimmed_rrnadep_kneaddata_unmatched_1.fastq"
        "/scratch/midway3/sjarif/konzo_scratch/kneaddata/{sampname}_R1_001_kneaddata_trimmed_rrnadep_kneaddata_unmatched_2.fastq"
    threads: 2
    resources:
        mem_mb=60000,
        runtime=2000
    params:
        job_name = 'kneaddata_dehost'
    run:
        shell('kneaddata \
        --input1 {input.fwd_in} \
        --input2 {input.rvs_in} \
        --output /scratch/midway3/sjarif/konzo_scratch/kneaddata \
        --threads 2 \
        --bypass-trim \
        --bypass-trf \
        --reference-db /project/blekhman/sjarif/konzo/db/human_rna_db')